gsheet_url = ""
gsheet_name = "ShieldGuard Interview Hub"
gsheet_name = "Hud Security Interview Hub"
drive_parent_folder_id = ""
audio_root_folder_name = "ShieldGuard Interview Audio"
audio_root_folder_name = "Hud Security Interview Audio"
default_share_email = "entremotivator@gmail.com"
admin_username = "admin"
admin_password = "HudSecurity2026!"
[gcp_service_account]
type = "service_account"
